print-status: False
flask-specific-port: flask run --host=${api.server.host} --port=${api.server.port}

api:
    name: FeatureManager
    extension: yml
    dependency:
        update: False
        list:
            web: [globals,python_helper,Popen,Path,numpy,pywin32,sqlalchemy]
    git:
        force-upgrade-command: pip install --upgrade --force python_framework
    static-package: AppData\Local\Programs\Python\Python38-32\statics
    list: []

    security:
        secret: default
    server:
        scheme: https
        host: feature-dataset-manager.herokuapp.com
        port: ''
        base-url: /api
    database:
        dialect: ${DATABASE_DIALECT:postgres}
        driver: ${DATABASE_DIALECT:psycopg2}
        database: ${DATABASE_NAME:d7dbsap9b1oecd}
        username: ${DATABASE_USERNAME:tbuwcalrrnvpxo}
        password: ${DATABASE_PASSWORD:cbc6bb13f6042a06fd0795afd8ba44d7c43d5da1dc56a8cce96b4e85767f383e}
        host: ${DATABASE_HOST:ec2-54-159-138-67.compute-1.amazonaws.com}
        port: ${DATABASE_PORT:5432}
        schema: ${DATABASE_SCHEMA:dev-device-automation-api-schema}

swagger:
    host: ${api.server.host}
    schemes: [${api.server.scheme}]
    info:
        title: ${api.name}
        version: 0.0.1
        description: This is an api that manage samples and its features. The main goal is to retrieve the best sample match given a set of features
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
