print-status: False

api:
    server:
        scheme: http
        port: 5933
        host: 192.168.25.8
    security:
        secret: ${SECURITY_KEY:local-secret-key}


swagger:
    host: ${api.server.host}:${api.server.port}
