print-status: False

api:
    server:
        scheme: http
        port: 5000
        host: localhost
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        driver: ${DATABASE_DRIVER:}
        database: ${DATABASE_NAME:}
        username: ${DATABASE_USERNAME:}
        password: ${DATABASE_PASSWORD:}
        host: ${DATABASE_HOST:}
        port: ${DATABASE_PORT:5432}
        schema: ${DATABASE_SCHEMA:}
        settings:
            check_same_thread: False

swagger:
    host: ${api.server.host}:${api.server.port}
